### ISSUE TITLE
uip-1 - Independent Proof-of-Work algorithm

### ISSUE THREAD

**Issue by jyap808** [ubiq/UIPs#1]
Proposal for an independent proof-of-work algorithm for Ubiq. Sharing a proof-of-work algorithm with the larger Ethereum network opens us up to potential mining rig rental attacks.

**Comment by akx20000a** [comment]
@jyap808 Would like to share any workaround for anti-asic hardfork, is there anything I can refer about?

**Comment by jyap808** [comment]
Ubqhash implemented

https://blog.ubiqsmart.com/introducing-ubqhash-8fa515befd7
