### ISSUE TITLE
UIP-11 - Fee market change (EIP-1559)

### ISSUE THREAD

**Issue by iquidus** [ubiq/UIPs#11]
### Simple Summary

Enable EIP-1559, a transaction pricing mechanism that includes fixed-per-block network fee that is burned and dynamically expands/contracts block sizes to deal with transient congestion.

Increase minimum gas price from 10gwei to 80gwei.

### Abstract

There is a base fee per gas in protocol, which can move up or down each block according to a formula which is a function of gas used in parent block and gas target (block gas limit divided by elasticity multiplier) of parent block. The algorithm results in the base fee per gas increasing when blocks are above the gas target, and decreasing when blocks are below the gas target. The base fee per gas is burned. Transactions specify the maximum fee per gas they are willing to give to miners to incentivize them to include their transaction (aka: priority fee). Transactions also specify the maximum fee per gas they are willing to pay total (aka: max fee), which covers both the priority fee and the block’s network fee per gas (aka: base fee). The transaction will always pay the base fee per gas of the block it was included in, and they will pay the priority fee per gas set in the transaction, as long as the combined amount of the two fees doesn’t exceed the transaction’s maximum fee per gas.

The proposal will also increase the minimum gas price from 10 Gwei to 80 Gwei. This will result in TXs with increased UBQ costs but still extremely cheap by dollar value. At 80 Gwei, 0.002 UBQ (currently 0.0003 UBQ) would be a standard UBQ transfer cost and 0.03 UBQ would be a typical smart contract interaction cost.

The important part is that it will have a visible impact on UBQ that is burnt via EIP1559 and against the block rewards.

EIP  | omit or include
-- | --
1559 (Fee market change)  |  include

### Specification

Technical specifications for each EIP can be found at those documents respectively:

- [EIP-1559](https://eips.ethereum.org/EIPS/eip-1559): Fee market change

### Implementation

Adoption of the content of this UIP requires a hard fork as it introduces changes that are not backward compatible. 

This UIP can be activated alongside UIP-10, otherwise as a standalone hardfork.

Due to the nature of this proposal it will go through Escher governance.

### Proposed Timeline

TBD

**Comment by ZenithII** [comment]
This needs to be implemented alongside UIP-12 and UIP-13 to negate the effects of the increased inflation. In favor of this change!

**Comment by LessDaStress** [comment]
Agree with Zenithll. Having UIP-11 in place is almost like a pre-requisite to support UIP-12 and UIP-13.

**Comment by skywalk3rUBQ** [comment]
Conscious effort needs to be made to be a good landing spot for miners 'when' ETH goes POS. I think the raise in Gwei base sets a good precedent to be miner focused moving forward. For users today, like in Token Gallery, that raise in gas price wont really cause minting or buying or swaps on shinobi to become even remotely prohibitively expensive. While we are not trying to mimic high cost transaction fee, thought towards a miners best interest in this market state cannot be overlooked.
Obviously I am in favor, as this is needed for the subsequent UIPs which I am also in favor of.

**Comment by LessDaStress** [comment]
> Conscious effort needs to be made to be a good landing spot for miners 'when' ETH goes POS. I think the raise in Gwei base sets a good precedent to be miner focused moving forward. For users today, like in Token Gallery, that raise in gas price wont really cause minting or buying or swaps on shinobi to become even remotely prohibitively expensive. While we are not trying to mimic high cost transaction fee, thought towards a miners best interest in this market state cannot be overlooked. Obviously I am in favor, as this is needed for the subsequent UIPs which I am also in favor of.

You have a point there about 'when' ETH goes PoS and impact on miner. I still actively mine Ubiq for the block rewards. But I would rather see users, activities, projects and visibility increases. I think the hashrate will be there to secure the network.

**Comment by j40j** [comment]
The fee increase is minor relative to price so I don’t see an issue and this UIP is needed for subsequent UIPs.
