### ISSUE TITLE
UIP-15 - Change Block Rewards (Alternative) 

### ISSUE THREAD

**Issue by iquidus** [ubiq/UIPs#15]
### Simple Summary
This is an alternative proposal to #13 

Change block rewards to 1,000 UBQ per block, forever. (dependent on adoption of UIP-12 and rejection of UIP-13)

### Abstract

The current monetary policy is stepping down too aggressively in relation to other variables (such as price), having a negative impact on network security. As is, the final step down to 1 UBQ per block will leave us in a vulnerable place in terms of blockchain security. We have observed Ubiq's hash rate go down at each step down in rewards so we can assume hash rate would be around 1/4th of what it is now. 

With the proposed blocktime changes in UIP-12, we will reach 1UBQ per block much faster than originally anticipated.

This UIP proposes to change the block rewards to 1,000UBQ, forever. Bringing our emissions into a similar range as other, larger PoW networks such as ETC ($1million daily).

To counter this additional inflation, UIP-11 (EIP-1559) is recommended. 

UIP  | omit or include
-- | --
11 (Fee market change (EIP-1559)) |  include
12 (Reduce Target Time for Blocks)  |  include
13 (Change Block Rewards) | omit

### Specification

TODO

### Implementation

Adoption of the content of this UIP requires a hard fork as it introduces changes that are not backward compatible. 
This UIP is dependent on UIP-12 and should be activated alongside each other.
This UIP conflicts with UIP-13, only one, or neither, should be accepted.

### Proposed Timeline

TBD

**Comment by ElevenXi** [comment]
lmao, so 2 or 1000?
Nice.

**Comment by j40j** [comment]
Sir, this would greatly encourage me to mine. Please pump price though sir, mi famile.

*smiles in bathed sarcasm*

In all seriousness sir, this I would not vote for.

**Comment by iquidus** [comment]
> lmao, so 2 or 1000? Nice.

competing proposals are welcome. 1000 would bring us inline with what other networks are paying their miners, at current market price (this is the only reasoning for this number). The only point I wish to make, is even if #13 is accepted, we would still be massively under-paying them in comparison to other networks.

**Comment by j40j** [comment]
For those of us that are ignorant to the mining market, your participation in dialogue educates some of us on the subject as you’re our only means to said topic. Therefore, your perspective is valued and pivotal in the community making educated decisions. I trust your stance and perspective so I’m on board with 2Ubq per block. Hell, you’ve convinced me to change it to 4 or 8 😎

**Comment by halop** [comment]
supply and demand

If you increase the supply like in this proposal, Ubiq quickly reaches the value of 1 Ubiq = 1 Sat

**Comment by hekkort** [comment]
Sounds like this will attract miners in the short term, price nukes, and then miners leave again because chain is at the same state it was before this proposal in terms of dollar/hashrate.
