### ISSUE TITLE
UIP-16 - Change block rewards + Consolidate hard forks to one hard fork

### ISSUE THREAD

**Issue by jyap808** [ubiq/UIPs#16]
### Simple summary

This UIP will combine the hard forks in UIP #10  and UIP #14 into 1 hard fork.

This UIP will also incorporate UIP #11, UIP #12 and a modified version of UIP #13.

We will also skip the Escher vote as we have gathered enough surrounding community feedback.

### Abstract

The core developers have discussed and we would like to implement the changes ASAP based on community feedback.

This will allow us to implement these consensus changes in the most efficient and safest way possible.

#### Combined hard fork

UIP #10 and UIP #14 are set up as 2 hard forks however these require additional code and testing to separate out EIP-1559 code. It is much more easier and safer to do this **without** the additional code and in one hard fork.

This UIP proposes performing 1 hard fork.

#### Modified UIP #13

Community feedback has mentioned that the UIP #13 setting of 2 UBQ is "too high". As the surrounding UIPs (UIP #11, UIP #12) also change monetary policy, we must implement them ALL as they complement and balance each other out.

This UIP changes the setting of UIP #13 to 1.5 UBQ per block and is based on community feedback.

#### No Escher vote for this UIP

Since we have gathered enough surrounding community feedback, there will be no Escher vote on this implementation.

Performing an Escher vote will require extra development to a new voting system based on Snapshot.

Performing an Escher vote will also lead to further delays on what we consider to be strong community consensus on the path forward.

### Implementation

All the above changes will be implemented in a hard fork.

**Comment by iquidus** [comment]
This UIP has my full support.

**Comment by johndoe1827** [comment]
This UIP has my full support

**Comment by weifageo** [comment]
Great to see the modified UIP-13 based on the community feedback.  I fully support this UIP as well.

**Comment by svenrenhoek** [comment]
We could use Escher if the voting period is greater than a few days - that way we can provide users an opportunity to unstake, vote, and restake, when gas prices are low.

**Comment by jyap808** [comment]
> We could use Escher if the voting period is greater than a few days - that way we can provide users an opportunity to unstake, vote, and restake, when gas prices are low.

The goal of this UIP is to reduce implementation time, extra development and improved safety.

Further discussion of using Escher would involve voting on UIP 13. This UIP does not involve Escher voting and takes into account discussions made on prior UIPs.

**Comment by jyap808** [comment]
This UIP has my full support.

**Comment by svenrenhoek** [comment]
> > We could use Escher if the voting period is greater than a few days - that way we can provide users an opportunity to unstake, vote, and restake, when gas prices are low.
> 
> The goal of this UIP is to reduce implementation time, extra development and improved safety.
> 
> Further discussion of using Escher would involve voting on UIP 13. This UIP does not involve Escher voting and takes into account discussions made on prior UIPs.

Understood. It's not a contentious issue for me.

This UIP has my full support.

**Comment by LessDaStress** [comment]
Thank you all for sharing your feedback, opinion and debating the UIPs. For someone like me who is still learning, this has been very enlightening. Learned a lot and happy to be part of this.

Considering all the arguments put forward, this UIP has my full support. Looking forward to see this UIP implemented soon.

**Comment by jpatel888** [comment]
This UIP has my full support.

**Comment by ElevenXi** [comment]
This UIP has my full support

**Comment by hekkort** [comment]
This UIP has my full support, gm

**Comment by Bullchad123** [comment]
Full support this UIP has from me

**Comment by halop** [comment]
full support ;-D

**Comment by outragedhuman** [comment]
This UIP has my full support

**Comment by crp9** [comment]
Affirmative, this UIP has my support. Was a very insightful venture to be a part of this system and how my questions were answered cheers!

**Comment by erikrijn** [comment]
Full support from me.

**Comment by skywalk3rUBQ** [comment]
Full speed ahead!

**Comment by jeewaka** [comment]
My full support to this UIP

**Comment by ZenithII** [comment]
This uip has my full support

**Comment by maaatttt** [comment]
UIP-16 has my full support.

**Comment by jyap808** [comment]
Closing issue. Pending hard fork.
