### ISSUE TITLE
UIP4 - Escher Logo Selection

### ISSUE THREAD

**Issue by krislester123** [ubiq/UIPs#4]
The purpose of this UIP is to outline the submission and selection process for all designers who wish to submit a logo design for the bounty. 

**Submission Criteria** 

- Each user will be allowed to submit 3 of their best designs for consideration.

- The designs must be vectors (.svg format) and must be uploaded in a zip file as GitHub does not allow .svg extensions to be attached. 

- Users must attach designs as a comment under this GitHub thread.

- Users must declare their discord username so we can contact them about the bounty.

**Selection Criteria**

- Depending on the number of submissions, voting may take place over one or two phases. If there are a large number of submissions the top voted options will be taken into round two, to ensure that one option does not win by collecting 5% of the total vote for example.

- If there are a large number of submissions and one option clearly wins by a majority, this will be selected without the need for phase two of voting.

- Voting will take place over a 2 week period for phase one and another 1 week period for phase two if necessary. 

**Bounty**

- 150 UBQ will be paid to the winner, upon selection.

**Comment by mbcharles** [comment]
CryptoQuan#0021
[Escher.zip](https://github.com/ubiq/UIPs/files/2557612/Escher.zip)

**Comment by TunaChum** [comment]
[Escher A_B_C.zip](https://github.com/ubiq/UIPs/files/2566242/Escher.A_B_C.zip)

**Comment by TunaChum** [comment]
![escher_a](https://user-images.githubusercontent.com/44901338/48268742-21215680-e436-11e8-9d1f-36b26def5214.png)
![escher_b](https://user-images.githubusercontent.com/44901338/48268743-21215680-e436-11e8-9602-62d9561efaeb.png)
![escher_c](https://user-images.githubusercontent.com/44901338/48268744-21215680-e436-11e8-8a14-5969fc19bc7d.png)

**Comment by TunaChum** [comment]
Discord username: TunaChum#1098

**Comment by TunaChum** [comment]
[EschContest.zip](https://github.com/ubiq/UIPs/files/2566829/EschContest.zip)
 These are JPEG to SVG files. Hope this one does work.

**Comment by krislester123** [comment]
DAVIDoperats 3 submissions, converted to png. Thanks!

![logo1](https://user-images.githubusercontent.com/29441296/48413611-2c2efc00-e740-11e8-8c79-b10c4ce20b2b.png)
![logo2](https://user-images.githubusercontent.com/29441296/48413612-2cc79280-e740-11e8-91b8-7d2041a832f9.png)
![logo3](https://user-images.githubusercontent.com/29441296/48413613-2cc79280-e740-11e8-848c-319d081c6aa2.png)

**Comment by kbrls** [comment]
discord : kbrls#0771

[escher.zip](https://github.com/ubiq/UIPs/files/2602996/escher.zip)

![escher](https://user-images.githubusercontent.com/34908400/48823761-21ddb500-ed73-11e8-86ec-73f2710d160f.png)

**Comment by ElevenXi** [comment]
Fiverr design funded by myself. 
[Ubiq Logo Icon AI.zip](https://github.com/ubiq/UIPs/files/2616271/Ubiq.Logo.Icon.AI.zip)

**Comment by ElevenXi** [comment]
![ubiq-logo-icon-png](https://user-images.githubusercontent.com/11433020/49025217-099ce880-f200-11e8-8f37-59f6c1c127dd.png)

**Comment by presCRYPTOmeds** [comment]
discord: presCRYPTO_meds#7555

[EscherUIP4.zip](https://github.com/ubiq/UIPs/files/2659768/EscherUIP4.zip)

**Comment by presCRYPTOmeds** [comment]
![escher2](https://user-images.githubusercontent.com/45715048/49687249-823c5880-face-11e8-917f-f7c6201f6814.png)

**Comment by krislester123** [comment]
Submitting this on behalf of Tiny Reee (discord: @Tiny Reee#8888) 

![image](https://user-images.githubusercontent.com/29441296/52266293-ef813400-292d-11e9-97a5-138ea5f2710e.png)

svg file will follow

**Comment by TunaChum** [comment]
[EschLogoTunaChum.zip](https://github.com/ubiq/UIPs/files/2941032/EschLogoTunaChum.zip)

These are my designs converted to .svg ( finally;) )
tunachum#1098

**Comment by iquidus** [comment]
Submissions closed.

Voting contract will be deployed.
