### ISSUE TITLE
uip-5 - Escher to become an Escher Hub on the Cosmos Network with ESCH as the native staking token

### ISSUE THREAD

**Issue by jyap808** [ubiq/UIPs#5]
Proposal for Escher (ESCH) to transition from an UBQ token to the base unit and native staking token of an Escher Hub on the Cosmos Network. This will retain Escher governance functionality as well as provide Ubiq with the benefits of running a  Hub on the Cosmos Network, enabling technologies such as Inter-Blockchain Communications (IBC).

From the outset, Escher was built as the governance token of the Ubiq network which fuels and directs proposals (development and otherwise). It was always envisioned that Escher would also provide additional utility to the Ubiq ecosystem.

**Comment by sjdimare** [comment]
Love to see the growth of Escher and the Ubiq ecosystem.

**Comment by steelctyboy** [comment]
Excited for this to go to vote.
