### ISSUE TITLE
UIP6 - Contribute 0.5 BTC from the NDF to list Ubiq, GeoCoin and Sphere on CryptoBridge DEX

### ISSUE THREAD

**Issue by weifageo** [ubiq/UIPs#6]
### Motivation
GeoCoin developer Dave Mancini has reached out to the CryptoBridge developers to enquire about the potential to list Ubiq, GeoCoin and Sphere on the CryptoBridge DEX.  After discussing individually about adding GeoCoin to CryptoBridge they offered our community a discounted price for adding the Ubiq custom protocol and the GeoCoin and Sphere ERC20 tokens to their DEX.  The majority of this listing fee has been sourced from donations in the network and community, the remaining portion of the listing fee is 0.5 BTC.

This proposal is to gauge community interest in the CryptoBridge DEX and determine whether the community would be willing to contribute this remaining 0.5 BTC from the Network Development Fund (NDF) to fulfill the listing fee.  CryptoBridge operates a DEX built on the BitShares network.  This could provide the community with a new non-KYC exchange for international users of Ubiq, GeoCoin and Sphere to trade.

### Specification
We can use 0.5 BTC from the NDF to contribute to this listing fee, choose not to contribute 0.5 BTC from the NDF or to abstain from voicing opinions during the vote while still showing participation.

### Implementation
If the community agrees to use 0.5 BTC from the NDF the funds will be gathered and sent to the CryptoBridge developers for listing Ubiq, GeoCoin and Sphere on their DEX.  If the community disagrees the funds would need to be sourced from other providers or the listing application could be abandoned.

### Voting Period
Propose that we run this over a voting period of 14,000 blocks with a minimum participation threshold of 20%.

### References
The most recent balances for the NDF fund are listed in the May 2019 Quarterly Report: https://blog.ubiqsmart.com/ubiq-quarterly-report-may-2019-bc467aaa4b4f

**Comment by sjdimare** [comment]
Could this listing include $SPHR since it is also on the Ubiq blockchain?  I am for the new listing in either case but just wondering if listing would include Sphere.

**Comment by weifageo** [comment]
This listing would include the Ubiq custom protocol and the GeoCoin ERC20 token only.  If the $SPHR developer, or any other token developer is interested in participating as well please contact me and I will happily discuss this addition with the CryptoBridge developers.

**Comment by ErwinKats** [comment]
Thank you for mentioning SPHR! We would be very pleased to be part of this arrangement with cryptobridge. This would add value and oppurtunity for our users who do not wish to interact with KYC exchanges.

**Comment by iquidus** [comment]
Awesome guys. GEO/SPHR teams, once you have worked out the details update the UIP so we can move this along.

**Comment by weifageo** [comment]
Thanks for the feedback, I've discussed this opportunity with the CryptoBridge devs and they're interested in adding additional markets.  I've updated the UIP to include Sphere

**Comment by steelctyboy** [comment]
Getting UBQ, GEO, and SPHR onto a dex should be a positive thing. I’ll definitely look forward to voting my support on UIP6.

**Comment by iquidus** [comment]
The voting contract has been deployed: https://ubiqsmart.com/escher/proposal/0x0fc21e12caa355bf96528deffb1ea0a6914075cb
